#! /bin/sh

#     _    _ _
#    / \  | (_) __ _ ___  ___  ___
#   / _ \ | | |/ _` / __|/ _ \/ __|
#  / ___ \| | | (_| \__ \  __/\__ \
# /_/   \_\_|_|\__,_|___/\___||___/
#

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ip='ip --color=auto'
alias tree='tree -C'
alias mv='mv -iv'
alias cp='cp -riv'
alias rm='rm -iv'
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
alias dd='dd bs=1024 status=progress'
alias ncdu='ncdu -x --exclude-kernfs --exclude Cloud /' 
alias w3m='w3m -no-cookie'

alias plz='sudo $(fc -ln -1)'
alias la='ls -lhA'
alias ll='ls -lh'
alias l1='ls -1'
alias lr='ls -R'
alias ldot='ls -lhd .*'
alias ..='cd ..'
alias untar='tar -zxvf'
alias wttr='curl wttr.in/Trondheim'
alias wttr-moon='curl wttr.in/moon'
alias clock='tty-clock -cC 4'
alias pth="echo $PATH | sed 's/:/\n/g'"
alias nvmestat='sudo nvme smart-log /dev/nvme0n1'
# alias cat-tags='cat tags | sed "/^!/d" | cut -f 1,2 | less'
# alias fsxl='convert $(fzf --reverse --multi --height=40%) -geometry 800x480 sixel:-'
alias docker='podman'
alias slcomp='sudo rm config.h && sudo make install'
alias fcd='cd $(find -L . -path "*/\\.*" -prune -o -type d | fzf --reverse --height=40% --border=sharp --preview="ls -l {}")'

alias e="$EDITOR"
alias f='lfimg'
alias se='sudoedit'
alias sush='sudo -E -s'
alias g='git'
alias o='opener'
alias rss='newsboat -q'
alias pod='podboat'
# alias rss='SFEED_PLUMBER_INTERACTIVE=1 SFEED_PLUMBER=w3m sfeed_curses $XDG_DATA_HOME/sfeed/*'
alias mail='neomutt'
alias p='pacman'
alias sp='sudo pacman'
alias pfr="yay -Qeq | fzf --multi --preview 'yay -Qi {1}' | xargs -ro yay -Rns"
alias pfs="yay -Slq | fzf --multi --preview 'yay -Si {1}' | xargs -ro yay -S"
alias pfu="yay -Qau | fzf --multi | cut -d' ' -f1 | xargs -ro yay -S"
