#! /bin/sh

#     _    _ _
#    / \  | (_) __ _ ___  ___  ___
#   / _ \ | | |/ _` / __|/ _ \/ __|
#  / ___ \| | | (_| \__ \  __/\__ \
# /_/   \_\_|_|\__,_|___/\___||___/
#

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ip='ip --color=auto'
alias tree='tree -C'
alias mv='mv -iv'
alias cp='cp -riv'
alias rm='rm -iv'
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
alias dd='dd bs=1024 status=progress'
alias ncdu='ncdu -x --exclude-kernfs --exclude Cloud /' 
alias w3m='w3m -no-cookie'

alias plz='sudo $(fc -ln -1)'
alias la='ls -lhA'
alias ll='ls -lh'
alias lr='ls -R'
alias pth="echo $PATH | sed 's/:/\n/g'"
alias nvmestat='sudo nvme smart-log /dev/nvme0n1'
alias slcomp='sudo rm config.h && sudo make install'
alias fcd='cd $(find -L . -path "*/\\.*" -prune -o -type d | fzf --reverse --height=40% --border=sharp --preview="ls -l {}")'

alias e="$EDITOR"
alias se='sudoedit'
alias sush='sudo -E -s'
alias f='clifm --icons -E'
alias t='tmux'
alias g='git'
alias rss='newsboat -q'
alias pod='podboat'
alias mail='neomutt'
alias p='pacman'
alias sp='sudo pacman'
alias pfr="yay -Qeq | fzf --multi --preview 'yay -Qi {1}' | xargs -ro yay -Rns"
alias pfs="yay -Slq | fzf --multi --preview 'yay -Si {1}' | xargs -ro yay -S"
alias pfu="yay -Qau | fzf --multi | cut -d' ' -f1 | xargs -ro yay -S"
