#!/bin/sh

scriptdir="$HOME/.local/bin"
rootdir="$scriptdir/dotfiles"
themedir="$rootdir/themes"
configdir="$rootdir/config"

SetTheme() {
    colbg=$(grep "bg=" "$1" | cut -d"=" -f2)
    colfg=$(grep "fg=" "$1" | cut -d"=" -f2)

    colbk1=$(grep "black1=" "$1" | cut -d"=" -f2)
    colbk2=$(grep "black2=" "$1" | cut -d"=" -f2)
    colre1=$(grep "red1=" "$1" | cut -d"=" -f2)
    colre2=$(grep "red2=" "$1" | cut -d"=" -f2)
    colge1=$(grep "green1=" "$1" | cut -d"=" -f2)
    colge2=$(grep "green2=" "$1" | cut -d"=" -f2)
    colye1=$(grep "yellow1=" "$1" | cut -d"=" -f2)
    colye2=$(grep "yellow2=" "$1" | cut -d"=" -f2)
    colbl1=$(grep "blue1=" "$1" | cut -d"=" -f2)
    colbl2=$(grep "blue2=" "$1" | cut -d"=" -f2)
    colpu1=$(grep "purple1=" "$1" | cut -d"=" -f2)
    colpu2=$(grep "purple2=" "$1" | cut -d"=" -f2)
    colcy1=$(grep "cyan1=" "$1" | cut -d"=" -f2)
    colcy2=$(grep "cyan2=" "$1" | cut -d"=" -f2)
    colwh1=$(grep "white1=" "$1" | cut -d"=" -f2)
    colwh2=$(grep "white2=" "$1" | cut -d"=" -f2)

    themegtk=$(grep "gtk=" "$1" | cut -d"=" -f2)
    themeicon=$(grep "icon=" "$1" | cut -d"=" -f2)
    themecursor=$(grep "cursor=" "$1" | cut -d"=" -f2)
    themefont=$(grep "font=" "$1" | cut -d"=" -f2)

    # fnott
    sed -i "s/background=.*\$/background=$colfg/" "$configdir/fnott/fnott.ini"
    sed -i "s/border-color=.*\$/border-color=$colbg/" "$configdir/fnott/fnott.ini"
    sed -i "s/title-color=.*\$/title-color=$colbg/" "$configdir/fnott/fnott.ini"
    sed -i "s/summary-color=.*\$/summary-color=$colbg/" "$configdir/fnott/fnott.ini"
    sed -i "s/body-color=.*\$/body-color=$colbg/" "$configdir/fnott/fnott.ini"

    # foot
    sed -i "s/background=.*\$/background=$colbg/" "$configdir/foot/foot.ini"
    sed -i "s/foreground=.*\$/foreground=$colfg/" "$configdir/foot/foot.ini"

    sed -i "s/regular0=.*\$/regular0=$colbk1/" "$configdir/foot/foot.ini"
    sed -i "s/regular1=.*\$/regular1=$colre1/" "$configdir/foot/foot.ini"
    sed -i "s/regular2=.*\$/regular2=$colge1/" "$configdir/foot/foot.ini"
    sed -i "s/regular3=.*\$/regular3=$colye1/" "$configdir/foot/foot.ini"
    sed -i "s/regular4=.*\$/regular4=$colbl1/" "$configdir/foot/foot.ini"
    sed -i "s/regular5=.*\$/regular5=$colpu1/" "$configdir/foot/foot.ini"
    sed -i "s/regular6=.*\$/regular6=$colcy1/" "$configdir/foot/foot.ini"
    sed -i "s/regular7=.*\$/regular7=$colwh1/" "$configdir/foot/foot.ini"
    sed -i "s/bright0=.*\$/bright0=$colbk2/" "$configdir/foot/foot.ini"
    sed -i "s/bright1=.*\$/bright1=$colre2/" "$configdir/foot/foot.ini"
    sed -i "s/bright2=.*\$/bright2=$colge2/" "$configdir/foot/foot.ini"
    sed -i "s/bright3=.*\$/bright3=$colye2/" "$configdir/foot/foot.ini"
    sed -i "s/bright4=.*\$/bright4=$colbl2/" "$configdir/foot/foot.ini"
    sed -i "s/bright5=.*\$/bright5=$colpu2/" "$configdir/foot/foot.ini"
    sed -i "s/bright6=.*\$/bright6=$colcy2/" "$configdir/foot/foot.ini"
    sed -i "s/bright7=.*\$/bright7=$colwh2/" "$configdir/foot/foot.ini"

    # river
    sed -i "s/local bg_color = .*\$/local bg_color = '0x${colbg}'/" "$configdir/river/lua/conf.lua"
    sed -i "s/local color_focused = .*\$/local color_focused = '0x${colfg}'/" "$configdir/river/lua/conf.lua"
    sed -i "s/local color_unfocused = .*\$/local color_unfocused = '0x${colbk2}'/" "$configdir/river/lua/conf.lua"
    sed -i "s/local color_urgent = .*\$/local color_urgent = '0x${colre1}'/" "$configdir/river/lua/conf.lua"

    sed -i "s/local gtk_theme = .*\$/local gtk_theme = '${themegtk}'/" "$configdir/river/lua/conf.lua"
    sed -i "s/local icon_theme = .*\$/local icon_theme = '${themeicon}'/" "$configdir/river/lua/conf.lua"
    sed -i "s/local cursor_theme = .*\$/local cursor_theme = '${themecursor}'/" "$configdir/river/lua/conf.lua"
    sed -i "s/local font = .*\$/local font = '${themefont}'/" "$configdir/river/lua/conf.lua"

    # yambar
    sed -i "s/\&fgcolor .*\$/\&fgcolor ${colfg}ff/" "$configdir/yambar/config.yml"
    sed -i "s/\&bgcolor .*\$/\&bgcolor ${colbg}ff/" "$configdir/yambar/config.yml"
    sed -i "s/\&graycolor .*\$/\&graycolor ${colbk2}4c/" "$configdir/yambar/config.yml"

    # Bemenu
    sed -i "s/ColorBlack=.*/ColorBlack='${colbk1}'/" "$configdir/shell/profile"
    sed -i "s/ColorBg=.*/ColorBg='${colbg}'/" "$configdir/shell/profile"
    sed -i "s/ColorFg=.*/ColorFg='${colfg}'/" "$configdir/shell/profile"
    sed -i "s/ColorHl=.*/ColorHl='${colre1}'/" "$configdir/shell/profile"
}

case "$1" in
    "theme" | "t")
        SetTheme "$themedir/$2"
        ;;
    "theme-menu" | "tm")
        ThemeSel=$(find "$themedir" -type f -printf "%f\n" | fzf)
        SetTheme "$themedir/$ThemeSel"
        ;;
    "deploy")
        if [[ -z "$2" ]]; then
            echo "Deploying everything ..."
            configs=$(find "$configdir" -maxdepth 1 -mindepth 1 -printf "%f\n")
            ln -s "$configdir/shell/profile" "$HOME/.zshenv"
            for ((i=1; i<=$(echo "$configs" | wc -l); i++)); do
                configname=$(echo "$configs" | sed -n "$i"p)
                ln -s "$configdir/$configname" "$XDG_CONFIG_HOME/$configname"
            done
        else
            echo "Deploying $2 ..."
            if [[ "$2" == "zsh" ]]; then
                ln -s "$configdir/zsh" "$XDG_CONFIG_HOME/zsh"
                ln -s "$configdir/shell" "$XDG_CONFIG_HOME/shell"
                ln -s "$configdir/shell/profile" "$HOME/.zshenv"
            else
                ln -s "$configdir/$2" "$XDG_CONFIG_HOME/$2"
            fi
        fi
        ;;
    "help")
        ;;
    *)
        git --git-dir=$scriptdir/.git --work-tree=$scriptdir "$@"
        ;;
esac
