#!/bin/sh

wallpaperdir="$HOME/Multimedia/Pictures/Wallpapers"


sel=$(imv "$wallpaperdir")

ln -s "$sel" "$wallpaperdir/current"
killall -q swaybg
swaybg -i "$sel" -m fill &
# imv "$wallpaperdir/*" | xargs -ro -I{} swaybg -i {} -m fill &
