#! /bin/sh

#    _    _ _
#   / \  | (_) __ _ ___  ___  ___
#  / _ \ | | |/ _` / __|/ _ \/ __|
# / ___ \| | | (_| \__ \  __/\__ \
#/_/   \_\_|_|\__,_|___/\___||___/
#

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias mv='mv -iv'
alias cp='cp -riv'
alias rm='rm -iv'
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
alias mocp='mocp -O MOCDir="$XDG_CONFIG_HOME"/moc'
alias dd='dd bs=1024 status=progress'
alias cat='bat -pp'

alias bm="$(printf "cat ~/.config/shell/bookmarks.txt" | column -t -s "  ")"
# alias bm='printf "$(cat ~/.config/shell/bookmarks.txt)" | column -t -s " "'
alias bm='cat ~/.config/shell/bookmarks.txt'
alias plz='sudo $(fc -ln -1)'
alias nna='nnn -FdaoQH -P p'
alias la='echo " " && exa -bhal --icons'
alias ll='echo " " && exa -bhl --icons'
alias lgit='echo " " && exa -bhal --git'
alias lgr='echo " " && exa -bhalG'
alias lr='ls -R'
alias ldot='ls -lhd .*'
alias lm='ls -lA | less'
alias ..='cd ..'
alias vim='nvim'
alias untar='tar -zxvf'
alias sl-comp='sudo cp -v config.def.h config.h && sudo make clean install'
alias dotfiles='/usr/bin/git --git-dir=$HOME/.config/dotfiles/ --work-tree=$HOME'
alias wttr='curl wttr.in/Trondheim'
alias wttr-moon='curl wttr.in/moon'
alias clock='tty-clock -cC 4'
alias ecron='crontab -e'
alias secron="su -c $(printf "%q " "crontab -e")"
alias keycomp='pdflatex ~/.local/src/keybindings/keybindings.tex'
alias pics='sxiv -abrt ~/Multimedia/Pictures/*'
alias blconf='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias pth="echo $PATH | sed 's/:/\n/g'"
alias nvmestat='sudo nvme smart-log /dev/nvme0n1'
alias nna='tmux new -n NNN nnn -HdP p'
alias nnn='nnn -H'

# Pacman aliases
alias fps="pacman -Slq | fzf --multi --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S"
alias fpr="pacman -Qetq | fzf --multi --preview 'pacman -Qi {1}' | xargs -ro sudo pacman -Rns"
alias fys="yay -Slq | fzf --multi --preview 'yay -Si {1}' | xargs -ro yay -S"
alias fyr="yay -Qq | fzf --multi --preview 'yay -Qi {1}' | xargs -ro yay -Rns"
alias sp='sudo pacman'


# Generated
alias d='cd /home/simen/Documents/'
alias p='cd /home/simen/Multimedia/Pictures/'
alias m='cd /home/simen/Multimedia/Music/'
alias v='cd /home/simen/Multimedia/Videos/'
alias D='cd /home/simen/Downloads/'
alias c='cd /home/simen/.config/'
alias s='cd /home/simen/.local/bin/'
alias h='cd /home/simen/'
alias k='cd /home/simen/.local/src/linux/linux-5.10.7/'
alias S='cd /home/simen/.local/src/Suckless/'
alias t='cd /home/simen/.local/share/Trash/files/'
alias P='cd /home/simen/Documents/Projects/'
