#! /bin/sh

# ____  _          _ _       ____             __ _ _
#/ ___|| |__   ___| | |     |  _ \ _ __ ___  / _(_) | ___
#\___ \| '_ \ / _ \ | |_____| |_) | '__/ _ \| |_| | |/ _ \
# ___) | | | |  __/ | |_____|  __/| | | (_) |  _| | |  __/
#|____/|_| |_|\___|_|_|     |_|   |_|  \___/|_| |_|_|\___|
#

# Environment variables

# Standard applications
export EDITOR=nvim
export VISUAL=nvim
export BROWSER=firefox
export TERMINAL=st

# NNN
export NNN_ARCHIVE="\.(7z|bz2|gz|tar|tgz|zip|rar|xz)$"
export NNN_FCOLORS='0b0b0c24002424f61f111109'
export NNN_COLORS='4231'
export NNN_FIFO='/tmp/nnn.fifo'
export NNN_PLUG='p:preview-tui;s:suedit;f:fzcd;i:imgview;c:chksum;I:imgthumb;d:dragdrop;x:togglex'

# FZF
export FZF_DEFAULT_OPTS="--reverse --info=inline --cycle -1 -0 --color='bg:-1,bg+:-1,pointer:9,info:10'"
export FZF_DEFAULT_COMMAND='fd --type f -H'
export FZF_COMPLETION_TRIGGER='--'

# Other variables
export PATH=~/.config/emacs/bin:~/.local/bin/:$PATH
eval "`dircolors -b ~/.config/shell/dir_colors/nord`"

# Home cleaning
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export OCTAVE_HISTFILE="$XDG_CACHE_HOME/octave_hist"
export OCTAVE_SITE_INITFILE="$XDG_CONFIG_HOME/octave/octaverc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export DOOMDIR="$XDG_CONFIG_HOME/doom"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export LESSHISTFILE=-

# Functions
# Startx on login
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ];
    then exec startx "$XDG_CONFIG_HOME/X11/xinitrc"
fi

function fbm {
    bmpath=$(cat /home/simen/.config/shell/bookmarks.txt | fzf | awk '{print $3}')
    cd $bmpath
}

# Generated
export NNN_BMS='S:/home/simen/.local/src/Suckless/;k:/home/simen/.local/src/linux/linux-5.10.7/;h:/home/simen/;s:/home/simen/.local/bin/;c:/home/simen/.config/;D:/home/simen/Downloads/;v:/home/simen/Multimedia/Videos/;m:/home/simen/Multimedia/Music/;p:/home/simen/Multimedia/Pictures/;d:/home/simen/Documents/;'
