#!/bin/sh

#  __  ___       _ _
#  \ \/ (_)_ __ (_) |_
#   \  /| | '_ \| | __|
#   /  \| | | | | | |_
#  /_/\_\_|_| |_|_|\__|
#

userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Set display resolution
xrandr --output DisplayPort-0 --primary --mode 2560x1440 --pos 0x240 --rotate normal --output DisplayPort-1 --off --output DisplayPort-2 --off --output HDMI-A-0 --mode 1920x1080 --pos 2560x0 --rotate right

# Set keymap
setxkbmap no &

#---Start applications/daemons---

# Start redshift
redshift -c ~/.config/redshift/redshift.conf &

# Set wallpaper
feh --bg-fill --no-fehbg --randomize ~/Multimedia/Pictures/Wallpapers/* &

# Start compositor
picom --config ~/.config/picom.conf &

# Mount the clouds
rclone mount msod:/ --daemon /home/simen/Cloud/OneDrive/ &
rclone mount drbo:/ --daemon /home/simen/Cloud/Dropbox/ &
rclone mount gldr:/ --daemon /home/simen/Cloud/GDrive/ &

# Start the polkit agent
lxsession &

# Start the notification server
dunst &

# Start the clipboard deamon
clipmenud &

#---Start the window-manager---

# Start alone
# exec dwm

# Start in dbus session (needed for spotify to work with MPRIS)
# exec dbus-launch --autolaunch=$(cat /etc/machine-id) dwm

# Start in dbus session with a script (allow resetting dwm without killing X)
exec dbus-launch --autolaunch=$(cat /etc/machine-id) startdwm.sh
