#!/bin/sh

#  __  ___       _ _
#  \ \/ (_)_ __ (_) |_
#   \  /| | '_ \| | __|
#   /  \| | | | | | |_
#  /_/\_\_|_| |_|_|\__|
#

userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Set display resolution

# Set keymap
setxkbmap no &


#---Start the window-manager---

# Start alone
# exec dwm

# Start in dbus session (needed for spotify to work with MPRIS)
# exec dbus-launch --autolaunch=$(cat /etc/machine-id) dwm

# Start in dbus session with a script (allow resetting dwm without killing X)
exec dbus-launch --autolaunch=$(cat /etc/machine-id) startdwm.sh
