#!/bin/sh

case "$1" in
    "up")
        /usr/bin/echo 0 > /sys/module/zswap/parameters/enabled
        /usr/bin/modprobe zram
        /usr/bin/echo "${ZRAM_COMPRESSION_ALGORITHM}" > /sys/block/zram0/comp_algorithm
        /usr/bin/echo "${ZRAM_SIZE}" > /sys/block/zram0/disksize
        /usr/bin/mkswap --label "${ZRAM_LABEL}" /dev/zram0
        /usr/bin/swapon --priority "${ZRAM_PRIORITY}" /dev/zram0
        ;;
    "down")
        /usr/bin/swapoff /dev/zram0
        /usr/bin/rmmod zram
        /usr/bin/echo 1 > /sys/module/zswap/parameters/enabled
        ;;
esac
