awesome: &awesome Font Awesome 5 Free:style=solid:pixelsize=20
fgcolor: &fgcolor e0def4ff
bgcolor: &bgcolor 232136ff
graycolor: &graycolor 817c9c4c
bar:
  height: 45
  location: top
  spacing: 5
  margin: 5

  # Default font
  #font: Hermit-Regular:pixelsize=12
  font: Terminus:pixelsize=28

  foreground: *fgcolor
  background: *bgcolor

  border:
    width: 0
    color: 999999cc
    margin: 0
    top-margin: 0
  left:
    - river:
        anchors:
          - base: &river_base
              margin: 5
              tag: id
          #default: {string: {text: , font: *awesome}}
              default: {string: {text: ""}}
              values:
                1: {string: {text: I}}
                2: {string: {text: II}}
                3: {string: {text: III}}
                4: {string: {text: IV}}
                5: {string: {text: V}}
                6: {string: {text: VI}}
                7: {string: {text: VII}}
                8: {string: {text: VIII}}
                9: {string: {text: IX}}
        content:
          map:
            tag: state
            values:
              focused:
                map:
                  tag: id
                  default: {empty: {}}
                  values:
                    1: {map: {<<: *river_base, deco: {stack: [background: {color: *graycolor}]}}}
                    2: {map: {<<: *river_base, deco: {stack: [background: {color: *graycolor}]}}}
                    3: {map: {<<: *river_base, deco: {stack: [background: {color: *graycolor}]}}}
                    4: {map: {<<: *river_base, deco: {stack: [background: {color: *graycolor}]}}}
                    5: {map: {<<: *river_base, deco: {stack: [background: {color: *graycolor}]}}}
                    6: {map: {<<: *river_base, deco: {stack: [background: {color: *graycolor}]}}}
                    7: {map: {<<: *river_base, deco: {stack: [background: {color: *graycolor}]}}}
                    8: {map: {<<: *river_base, deco: {stack: [background: {color: *graycolor}]}}}
                    9: {map: {<<: *river_base, deco: {stack: [background: {color: *graycolor}]}}}
              unfocused:
                map:
                  tag: id
                  default: {empty: {}}
                  values:
                    1: {map: {<<: *river_base, foreground: *graycolor}}
                    2: {map: {<<: *river_base, foreground: *graycolor}}
                    3: {map: {<<: *river_base, foreground: *graycolor}}
                    4: {map: {<<: *river_base, foreground: *graycolor}}
                    5: {map: {<<: *river_base, foreground: *graycolor}}
                    6: {map: {<<: *river_base, foreground: *graycolor}}
                    7: {map: {<<: *river_base, foreground: *graycolor}}
                    8: {map: {<<: *river_base, foreground: *graycolor}}
                    9: {map: {<<: *river_base, foreground: *graycolor}}
              invisible:
                map:
                  tag: id
                  default: {empty: {}}
                  values:
                    1: {map: {<<: *river_base, foreground: *graycolor}}
                    2: {map: {<<: *river_base, foreground: *graycolor}}
                    3: {map: {<<: *river_base, foreground: *graycolor}}
                    4: {map: {<<: *river_base, foreground: *graycolor}}
                    5: {map: {<<: *river_base, foreground: *graycolor}}
                    6: {map: {<<: *river_base, foreground: *graycolor}}
                    7: {map: {<<: *river_base, foreground: *graycolor}}
                    8: {map: {<<: *river_base, foreground: *graycolor}}
                    9: {map: {<<: *river_base, foreground: *graycolor}}

    - clock:
        time-format: "%H:%M"
        date-format: "%a %d/%m/%Y"
        content:
          - string: {text: "|| {date}", right-margin: 5}
          - string: {text: "{time}"}

  right:
    - battery:
        name: BAT0
        poll-interval: 30
        anchors:
          discharging: &discharging
            list:
              items:
                - string: {text: " {capacity}% |"}
        content:
          map:
            tag: state
            values:
              unknown:
                <<: *discharging
              discharging:
                <<: *discharging
              charging:
                - string: {text: " {capacity}% |"}
              full:
                - string: {text: " Full |"}
              not charging:
                - string: {text: "  {capacity}% |"}
    - network:
        name: wlp0s20f3
        content:
          map:
            on-click: /bin/sh -c
            tag: state
            default: {string: {text: " |", }}
            values:
              down: {string: {text: " |"}}
              up:
                map:
                  tag: ipv4
                  default:
                  - string: {text: " |"}
                  values:
                    "":
                    - string: {text: " |"}
    - backlight:
        name: intel_backlight
        content: [ string: {text: " {percent}% |"}]

    - alsa:
        card: default
        mixer: Master
        content:
          map:
            on-click: amixer -q sset Master toggle
            tag: muted
            values:
              true: {string: {text: ' |'}}
              false: {string: {text: ' {percent}% |'}}

    - script:
        path: /home/simen/.local/bin/blocks/upd.sh
        args: []
        content:
          map:
            tag: used
            default: { string: { text: " {pkg} |" } }
            values:
              0: {string: {text: ~~~}}

    - script:
        path: /home/simen/.local/bin/blocks/upt.sh
        args: []
        content:
          map:
            tag: used
            default: { string: { text: " {upt} |" } }
            values:
              0: {string: {text: ~~~}}

    - script:
        path: /home/simen/.local/bin/blocks/mem.sh
        args: []
        content:
          map:
            tag: used
            default: { string: { text: " {used} Mib |" } }
            values:
              0: {string: {text: ~~~}}
    - script:
        path: /home/simen/.local/bin/blocks/cpu_temp.sh
        args: [] 
        content:
          map:
            tag: cpu
            default: { string: { text: " {cpu}°C |" } }
            values:
              0: {string: {text: no updates}}

    - label:
        content:
          string:
            on-click: "playerctl previous"
            text: '  '
    - label:
        content:
          string:
            on-click: "playerctl play-pause"
            text: ' '
            # foreground: 'cc241dff'
    - label:
        content:
          string:
            on-click: "playerctl next"
            text: ' '
