#!/bin/sh

_fzfargs="--height=40% --reverse --border=sharp"

case "$1" in
  "show")
    git log --oneline --graph --color=always \
      | fzf $_fzfargs --ansi --preview='echo {} | sed "s/^\W*//" | cut -f1 -d" " | xargs git show --color=always' \
      | sed 's/^\W*//' \
      | cut -f1 -d" " \
      | xargs -ro git show
    ;;
  "add")
    git status --short \
      | fzf $_fzfargs --multi --preview='git diff {-1}' \
      | awk '{$1="";print}' \
      | xargs git add
    ;;
  *)
    echo "Supported commands:
  show
  add"
    ;;
esac
