#!/bin/sh

litdir="$HOME/Documents/notatsys/doks/litteratur"

read_file="$litdir/$(find $litdir -type f -printf '%P\n' | grep -E "^.*\.(pdf|djvu|epub|chm|ps|html)$" | fzf)"

if [ ! -f "$read_file" ]
then
    exit 0
fi

write_file="$HOME/Documents/notatsys/wiki/boknotat:$(echo "$read_file" | grep -Po "[^/]*(?=\.\w*$)" | tr '[:upper:]' '[:lower:]').md"

st -e $EDITOR "$write_file" &
opener "$read_file"
