#!/usr/bin/env bash

notatsyspath="$HOME/Documents/notatsys"
wikipath="$notatsyspath/wiki"
templatepath="$notatsyspath/.templates"
journalpath="$notatsyspath/journal"
contactspath="$notatsyspath/kontakter"
calfile="$notatsyspath/kalender.md"
litdir="$notatsyspath/doks/litteratur"
finder="fzf --reverse --border=rounded --cycle --height=40%"

searchTags() {
  tags=$(grep -roP "(?<=#)[_a-åA-Å0-9]*(?=(\s|$))" "$wikipath" | cut -d':' -f2 | sort | uniq -c)
  sel_tag=$(echo "$tags" | $finder | awk '{print $2}')
  if [ "$sel_tag" == "" ]
  then
    exit
  fi
  sel_note=$(grep -roP "(?<=#)$sel_tag(?=(\s|$))" "$wikipath" | cut -d':' -f1 | sed "s|^$wikipath/||" | sort | $finder --preview="less $wikipath/{}")
  if [ "$sel_note" == "" ]
  then
    exit
  fi
  $EDITOR "$wikipath/$sel_note"
}

findNote() {
  sel_note=$(find "$wikipath" -type f -printf "%C@ %P\n" | sort | cut -d' ' -f2 | $finder)
  if [ "$sel_note" == "" ]
  then
    exit
  fi
  $EDITOR "$wikipath/$sel_note"
}

printDay() {
  day_file="$journalpath/$1"
  if [ -f "$day_file" ]
  then
    echo ""
    cat "$day_file"
    echo ""
  else
    echo -e "\nIngenting på planen så langt\n"
  fi
}

newNote() {
  day_file="$journalpath/$2"
  echo " - $1" >> "$day_file"
}

newTask() {
  day_file="$journalpath/$2"
  echo " [ ] $1" >> "$day_file"
}

wiki() {
  case "$2" in
    "tags" | "t")
      searchTags
      ;;
    *)
      findNote
      ;;
  esac
}

lit() {
  read_file="$litdir/$(find "$litdir" -type f -printf '%P\n' | grep -E "^.*\.(pdf|djvu|epub|chm|ps|html)$" | fzf)"

  if [ ! -f "$read_file" ]
  then
    exit 0
  fi

  write_file="$HOME/Documents/notatsys/wiki/boknotat:$(echo "$read_file" | grep -Po "[^/]*(?=\.\w*$)" | tr '[:upper:]' '[:lower:]').md"

  st -e $EDITOR "$write_file" &
  opener "$read_file"
}

printHelp() {
  echo "
wiki tags
  Search notes based on tag
wiki find
  Search notes
desktop
  Open desktop file in EDITOR
cal DATE
  Show calender for date
edcal
  Edit calender
lit
  Open document and notes
pdf
  Convert note to pdf
commit
  Commit changes
log
  Show all changes
checkout
  View specific commit
"
}

case "$1" in
  "wiki" | "w")
    wiki "$@"
    ;;
  "journal" | "j")
    journal "$@"
    ;;
  "desktop" | "")
    $EDITOR "$notatsyspath/skrivebord.md"
    ;;
  "cal")
    day=$(date +"%Y-%m-%d" -d "$2")
    grep "$day" "$calfile" | sed 's/|/\n/g'
    ;;
  "edcal")
    $EDITOR "$calfile"
    ;;
  "lit")
    lit
    ;;
  "pdf")
    pandoc -t pdf "$2" -o - | zathura -
    ;;
  "commit")
    git commit -am "Endringer"
    ;;
  "log")
    git log
    ;;
  "checkout")
    git checkout "$2"
    ;;
  *)
    printHelp
    ;;
esac
