#!/bin/sh

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
xrandr --output DisplayPort-0 --primary --mode 2560x1440 --pos 0x240 --rotate normal --output DisplayPort-1 --off --output DisplayPort-2 --off --output HDMI-A-0 --mode 1920x1080 --pos 2560x0 --rotate right

sv import-env DISPLAY
sv import-env XAUTHORITY
sv import-env XDG_VTNR
sv import-env XDG_SEAT
sv import-env XDG_SESSION_ID
sv import-env XDG_SESSION_CLASS
sv import-env XDG_SESSION_TYPE
sv up session-xorg

# Start wm
exec dwm-start
