#!/bin/sh


userresources=$XDG_CONFIG_HOME/X11/xresources
usermodmap=$XDG_CONFIG_HOME/X11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Configure display
xrandr --output DisplayPort-0 --primary --mode 2560x1440 --pos 0x240 --rotate normal --output DisplayPort-1 --off --output DisplayPort-2 --off --output HDMI-A-0 --mode 1920x1080 --pos 2560x0 --rotate right
xwallpaper --zoom ~/Multimedia/Pictures/Wallpapers/current

# Configure keyboard
# setxkbmap no
setxkbmap -model 'pc105' -layout 'no(cmk_ed_ks)' -option 'misc:extend,lv5:caps_switch_lock,grp:shifts_toggle,compose:menu,misc:cmk_curl_dh'
xset r rate 300 50
xset m default
xset b off

sv import-env DISPLAY
sv import-env XAUTHORITY
sv import-env XDG_VTNR
sv import-env XDG_SEAT
sv import-env XDG_SESSION_ID
sv import-env XDG_SESSION_CLASS
sv import-env XDG_SESSION_TYPE
sv up session-xorg

# Start wm
exec dwm-start
