#! /bin/sh

#     _    _ _
#    / \  | (_) __ _ ___  ___  ___
#   / _ \ | | |/ _` / __|/ _ \/ __|
#  / ___ \| | | (_| \__ \  __/\__ \
# /_/   \_\_|_|\__,_|___/\___||___/
#

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ip='ip --color=auto'
alias tree='tree -C'
alias mv='mv -iv'
alias cp='cp -riv'
alias rm='rm -iv'
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
alias dd='dd bs=1024 status=progress'
alias ncdu='ncdu -x --exclude-kernfs --exclude Cloud /' 

alias plz='sudo $(fc -ln -1)'
alias la='ls -lhA'
alias ll='ls -lh'
alias l1='ls -1'
alias lr='ls -R'
alias ldot='ls -lhd .*'
alias ..='cd ..'
alias untar='tar -zxvf'
alias wttr='curl wttr.in/Trondheim'
alias wttr-moon='curl wttr.in/moon'
alias clock='tty-clock -cC 4'
alias pth="echo $PATH | sed 's/:/\n/g'"
alias nvmestat='sudo nvme smart-log /dev/nvme0n1'
alias battery="upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep 'percentage' | sed 's/\s//g'"
alias cat-tags='cat tags | sed "/^!/d" | cut -f 1,2 | less'
alias fsxl='convert $(fzf --reverse --multi --height=40%) -geometry 800x480 sixel:-'

alias e="$EDITOR"
alias f='nnn'
alias se='sudoedit'
alias sush='sudo -E -s'
alias g='git'
alias o='xdg-open'
alias rss='newsboat -q'
alias mail='neomutt'
alias p='pacman'
alias sp='sudo pacman'
alias pfr="yay -Qq | fzf --multi --preview 'yay -Qi {1}' | xargs -ro yay -Rns"
alias pfs="yay -Slq | fzf --multi --preview 'yay -Si {1}' | xargs -ro yay -S"
alias pfu="yay -Qau | fzf --multi | cut -d' ' -f1 | xargs -ro yay -S"

# Abduco
alias a='abduco -e ^q'
dvtms() {
    abduco -e ^q -c "$1" dvtm-status -m ^a -t "$1"
}
dvtmb() {
    prevdir=$(pwd)
    cd "$2"
    abduco -e ^q -n "$1" dvtm-status -m ^a -t "$1"
    cd "$prevdir"
}

sxl() {
    echo ""
    convert  "$1"  -geometry 800x480  sixel:- 
    echo ""
}

# Tmux
alias tx='tmux'
alias t='tmux new-session -A -s 0'
alias txa='tmux attach-session'
alias txd='tmux detach-client'
alias txat='tmux attach -t'
alias txdt='tmux attach -d -t'
alias txk='tmux kill-server'
alias txkt='tmux kill-session -t'
alias txrn='tmux rename-session -t'
alias txls='tmux list-sessions'
alias txst='tmux new-session -s'
alias txld='tmuxp load'

# systemd
alias susc='sudo systemctl'
alias sc='systemctl --user'
alias suscls='sudo systemctl --type=service'
alias scls='systemctl --user --type=service'
alias scysserv='sudo systemctl --type=service'
alias scserv='systemctl --user --type=service'
alias susctimer='sudo systemctl --type=timer'
alias sctimer='systemctl --user --type=timer'
alias suscsocket='sudo systemctl --type=socket'
alias scsocket='systemctl --user --type=socket'

# Suite66
alias 66-intree='66-intree -zg'
alias 66-inservice='66-inservice -z'
alias 66-enable='66-enable -z'
alias 66-disable='66-disable -z'
alias 66-start='66-start -z'
alias 66-stop='66-stop -z'
alias 66-all='66-all -z'
alias 66-tree='66-tree -z'
alias 66-env='66-env -z -e $EDITOR'

alias 66-suintree='sudo 66-intree -zg'
alias 66-suinservice='sudo 66-inservice -z'
alias 66-suenable='sudo 66-enable -z'
alias 66-sudisable='sudo 66-disable -z'
alias 66-sustart='sudo 66-start -z'
alias 66-sustop='sudo 66-stop -z'
alias 66-suall='sudo 66-all -z'
alias 66-sutree='sudo 66-tree -z'
alias 66-suenv='sudo 66-env -z -e $EDITOR'
