#!/bin/sh

datafile="${_Z_DATA:-$HOME/.z}"
# Read the data from z's file instead of calling
# z so the data doesn't need to be processed twice
# sel=$(awk -F "|" '{print $1}' "$datafile" | fzf | awk '{$1=$1};1')

# NOTE: Uncomment this line and comment out the line above if
# you want to see the weightings of the dir's in the fzf pane
sel=$(awk -F "|" '{printf "%s %s\n", $2, $1}' "$datafile" | fzf | sed 's/^[0-9,.]* *//' | awk '{$1=$1};1')

printf "%s" "0c$sel" > "$NNN_PIPE"
